### ISSUE TITLE
Unable to read file 'dataset\totalR.mat' (could you upload the modifiable HDP or provide version of linux system?)

### ISSUE THREAD

**Issue by chialin6** [JoongcholShin/RRO-Dehazing#1]
I've encounterd
```
Error using load
Unable to read file 'dataset\totalR.mat'. No such file or directory.

Error in HDP

Error in Dehazing_2017_7_ShinJoongChol (line 85)
[t, Corse, d_J, d_Jtild]=HDP(img, ref2, A, w, phi,psai);
```
and I think it is because of the path ```\``` in windows
would you provide the modifiable HDP.m instead of HDP.p? 
or would provide the version that can loaded by linux system?
Thanks a lot!!!

**Comment by JoongcholShin** [comment]
I updated a main code ('Dehazing_2017_7_ShinJoongChol.m'), and it can modify the path (dataset\total*.mat).  
Please check the main code (line 88 - 90).
Thank you.

**Comment by chialin6** [comment]
Thank you so much!!!!

**Comment by chialin6** [comment]
Thank you so much!!!
